spring:
  application:
    name: spring-security-sample
  datasource:
    url: jdbc:sqlite:mydb.sqlite #mydb.sqlite is the name of the SQLite file. If you don?t have the file (at the project?s root), it will be automatically created.
    username: admin
    password: admin
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 30
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mustache:
    suffix: .html
    servlet:
      cache: false
logging:
  level:
    root: info
    org.mybatis: debug
    org.xerial: debug
#    com.zaxxer.hikari: debug
    org.springframework.security: debug
    com.tistory.aircook.security: debug


#security settings ------------------------------------------------------------------------------------
security:
  authenticated:
    exclude:
      - "/"
      - "/login"
      - "/login/failure"
      - "/public/test01"
      - "/users/**"
      - "/api/v1/login"
      - "login-form"
jwt:
  secret: Vm4K038c4nspS47dyroqkfwk6balAo4kf9kdba36hT8adfna2fdu032ihawSO05zG