-- 비밀번호: password01
INSERT INTO USERS(USERID, PASSWORD, ROLE) VALUES('user01', '{bcrypt}$2a$10$rwvnkh7468pSaALOPxAIgOpgkKFG9Cx3lIUPs21Z3E7ZeSf9jqxBy', 'ADMIN');
INSERT INTO USERS(USERID, PASSWORD, ROLE) VALUES('user02', '{bcrypt}$2a$10$fwyl8aaYp.O0odaxVC8DauJFSVlhXEy9WogoexRJmfVaIXibCIkKC', 'USER');
INSERT INTO USERS(USERID, PASSWORD, ROLE) VALUES('user03', '{bcrypt}$2a$10$egCLGQFrC/RdKgXOs7Fu7.j4Y8akyTRMgCFclR2XFDP8lR73pZCYy', 'USER');
INSERT INTO USERS(USERID, PASSWORD, ROLE) VALUES('user03', '{bcrypt}$2a$10$E0PU2iL8mrWJQLDxSfDSY.6jFoSTX70bwkvXRPzg7UYIxei85Ggji', 'USER');
INSERT INTO USERS(USERID, PASSWORD, ROLE) VALUES('user03', '{bcrypt}$2a$10$nRNo8jaotbmWXD0HiSmtMenb7x45smqIMpLYLdnbA5EqhDYFMwNiO', 'USER');