### Login and get JWT (in Response Header)
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = user01 &
password = password01

### Public test01
GET http://localhost:8080/public/test01

### Private test01, you need token to pass
GET http://localhost:8080/private/test01
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXIwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMTY5NTkxNCwiZXhwIjoxNzIxNjk1OTUwfQ.6gnFAq7xkEDpwWbvx7wNnjZCfN_7Im3toedU_SVjcHk


